-- MySQL Script generated by MySQL Workbench
-- 10/22/17 12:22:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombreEmpresa` VARCHAR(45) NULL,
  `personaContacto` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `marca` VARCHAR(60) NULL,
  `precio` VARCHAR(15) NULL,
  `categoria_idCategoria` INT NOT NULL,
  `proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_producto_categoria1_idx` (`categoria_idCategoria` ASC),
  INDEX `fk_producto_proveedor1_idx` (`proveedor_idProveedor` ASC),
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`categoria_idCategoria`)
    REFERENCES `mydb`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_proveedor1`
    FOREIGN KEY (`proveedor_idProveedor`)
    REFERENCES `mydb`.`proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombreEmpleado` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fechaContratacion` VARCHAR(45) NULL,
  `sueldo` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombreCliente` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `direccion` VARCHAR(90) NULL,
  `telefono` VARCHAR(14) NULL,
  `nif` VARCHAR(9) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidoCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidoCliente` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fechaPedido` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `empleado_idEmpleado` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedidoCliente_empleado1_idx` (`empleado_idEmpleado` ASC),
  INDEX `fk_pedidoCliente_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_pedidoCliente_empleado1`
    FOREIGN KEY (`empleado_idEmpleado`)
    REFERENCES `mydb`.`empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidoCliente_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detallePedido` (
  `idDetallePedido` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `subtotal` VARCHAR(45) NULL,
  `total` VARCHAR(45) NULL,
  `idPedido` VARCHAR(45) NULL,
  `pedidoCliente_idPedido` INT NOT NULL,
  PRIMARY KEY (`idDetallePedido`),
  INDEX `fk_detallePedido_pedidoCliente1_idx` (`pedidoCliente_idPedido` ASC),
  CONSTRAINT `fk_detallePedido_pedidoCliente1`
    FOREIGN KEY (`pedidoCliente_idPedido`)
    REFERENCES `mydb`.`pedidoCliente` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalleCompra` (
  `idDetalleCompra` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precioLista` VARCHAR(45) NULL,
  `descuento` VARCHAR(45) NULL,
  `subtotal` VARCHAR(45) NULL,
  `totalNeto` VARCHAR(45) NULL,
  `numOrden` VARCHAR(45) NULL,
  `producto_idProducto` INT NOT NULL,
  INDEX `fk_detalleCompra_producto1_idx` (`producto_idProducto` ASC),
  PRIMARY KEY (`idDetalleCompra`),
  CONSTRAINT `fk_detalleCompra_producto1`
    FOREIGN KEY (`producto_idProducto`)
    REFERENCES `mydb`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `fechaEmision` VARCHAR(45) NULL,
  `fechaVencimiento` VARCHAR(45) NULL,
  `detalleCompra_idDetalleCompra` INT NOT NULL,
  `proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_compra_detalleCompra1_idx` (`detalleCompra_idDetalleCompra` ASC),
  INDEX `fk_compra_proveedor1_idx` (`proveedor_idProveedor` ASC),
  CONSTRAINT `fk_compra_detalleCompra1`
    FOREIGN KEY (`detalleCompra_idDetalleCompra`)
    REFERENCES `mydb`.`detalleCompra` (`idDetalleCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_proveedor1`
    FOREIGN KEY (`proveedor_idProveedor`)
    REFERENCES `mydb`.`proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pruebas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pruebas` (
  `idpruebas` INT NOT NULL AUTO_INCREMENT,
  `nombrePrueba` VARCHAR(45) NULL,
  `aparatosNecesarios` VARCHAR(45) NULL,
  PRIMARY KEY (`idpruebas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prueba-cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prueba-cliente` (
  `pruebas_idpruebas` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  `diagnostico` VARCHAR(45) NULL,
  INDEX `fk_prueba-cliente_pruebas1_idx` (`pruebas_idpruebas` ASC),
  INDEX `fk_prueba-cliente_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_prueba-cliente_pruebas1`
    FOREIGN KEY (`pruebas_idpruebas`)
    REFERENCES `mydb`.`pruebas` (`idpruebas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prueba-cliente_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`categoria` (
  `idCategoria` INT(11) NOT NULL,
  `nombreCategoria` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`cliente` (
  `idCliente` INT(11) NOT NULL,
  `nombreCliente` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `direccion` VARCHAR(90) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `telefono` VARCHAR(14) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `nif` VARCHAR(9) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`proveedor` (
  `idProveedor` INT(11) NOT NULL,
  `nombreEmpresa` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `personaContacto` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `direccion` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`producto` (
  `idProducto` INT(11) NOT NULL,
  `nombreProducto` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `marca` VARCHAR(60) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `precio` VARCHAR(15) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `categoria_idCategoria` INT(11) NOT NULL,
  `proveedor_idProveedor` INT(11) NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_producto_categoria1_idx` (`categoria_idCategoria` ASC),
  INDEX `fk_producto_proveedor1_idx` (`proveedor_idProveedor` ASC),
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`categoria_idCategoria`)
    REFERENCES `optica`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_proveedor1`
    FOREIGN KEY (`proveedor_idProveedor`)
    REFERENCES `optica`.`proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`detallecompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`detallecompra` (
  `idDetalleCompra` INT(11) NOT NULL,
  `cantidad` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `precioLista` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `descuento` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `subtotal` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `totalNeto` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `numOrden` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `producto_idProducto` INT(11) NOT NULL,
  PRIMARY KEY (`idDetalleCompra`),
  INDEX `fk_detalleCompra_producto1_idx` (`producto_idProducto` ASC),
  CONSTRAINT `fk_detalleCompra_producto1`
    FOREIGN KEY (`producto_idProducto`)
    REFERENCES `optica`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`compra` (
  `idcompra` INT(11) NOT NULL,
  `fechaEmision` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `fechaVencimiento` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `detalleCompra_idDetalleCompra` INT(11) NOT NULL,
  `proveedor_idProveedor` INT(11) NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_compra_detalleCompra1_idx` (`detalleCompra_idDetalleCompra` ASC),
  INDEX `fk_compra_proveedor1_idx` (`proveedor_idProveedor` ASC),
  CONSTRAINT `fk_compra_detalleCompra1`
    FOREIGN KEY (`detalleCompra_idDetalleCompra`)
    REFERENCES `optica`.`detallecompra` (`idDetalleCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_proveedor1`
    FOREIGN KEY (`proveedor_idProveedor`)
    REFERENCES `optica`.`proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`empleado` (
  `idEmpleado` INT(11) NOT NULL,
  `nombreEmpleado` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `direccion` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `telefono` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `fechaContratacion` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sueldo` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`pedidocliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`pedidocliente` (
  `idPedido` INT(11) NOT NULL,
  `fechaPedido` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `cantidad` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `empleado_idEmpleado` INT(11) NOT NULL,
  `cliente_idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_pedidoCliente_empleado1_idx` (`empleado_idEmpleado` ASC),
  INDEX `fk_pedidoCliente_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_pedidoCliente_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `optica`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidoCliente_empleado1`
    FOREIGN KEY (`empleado_idEmpleado`)
    REFERENCES `optica`.`empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`detallepedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`detallepedido` (
  `idDetallePedido` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `cantidad` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `precio` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `subtotal` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `total` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `idPedido` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `pedidoCliente_idPedido` INT(11) NOT NULL,
  PRIMARY KEY (`idDetallePedido`),
  INDEX `fk_detallePedido_pedidoCliente1_idx` (`pedidoCliente_idPedido` ASC),
  CONSTRAINT `fk_detallePedido_pedidoCliente1`
    FOREIGN KEY (`pedidoCliente_idPedido`)
    REFERENCES `optica`.`pedidocliente` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`pruebas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`pruebas` (
  `idpruebas` INT(11) NOT NULL,
  `nombrePrueba` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `aparatosNecesarios` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`idpruebas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`prueba-cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`prueba-cliente` (
  `pruebas_idpruebas` INT(11) NOT NULL,
  `cliente_idCliente` INT(11) NOT NULL,
  `diagnostico` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  INDEX `fk_prueba-cliente_pruebas1_idx` (`pruebas_idpruebas` ASC),
  INDEX `fk_prueba-cliente_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_prueba-cliente_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `optica`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prueba-cliente_pruebas1`
    FOREIGN KEY (`pruebas_idpruebas`)
    REFERENCES `optica`.`pruebas` (`idpruebas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `optica`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`usuario` (
  `idusuario` INT(11) NOT NULL,
  `clave` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `contraseña` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `fecha` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
